import { Fragment } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Eyebrow } from "@/components/brand/magic";
import { Section, SectionHeading, SectionBody } from "@/components/marketing/section";
import { MonoStrip } from "@/components/marketing/mono-strip";
import { PricingFaq } from "@/components/marketing/pricing-faq";
import { PricingPlans } from "@/components/marketing/pricing-plans";
import { PLAN_LIMITS } from "@/lib/entitlements";
import { ANNUAL_MONTHLY_EQUIV_USD, ANNUAL_USD, MONTHLY_USD, PRICING_MATRIX_BANDS } from "@/lib/pricing";
import { cn } from "@/lib/utils";

// /pricing v2 (P9.5-T4) — poster head, banded matrix with sticky band
// headers, a real "band" guarantee Section, a split FAQ, and an air
// closing. Title/description only — file-based opengraph-image.png (+
// .alt.txt, generated by scripts/generate-brand-images.ts) owns the
// imagery; Next's metadata merge is shallow, so setting any part of
// `openGraph` here would replace the root layout's whole object instead of
// extending it. `title` is a plain string on purpose — the root layout's
// `title.template` ("%s · QRCDN") supplies the suffix. Description figures
// are interpolated from the same entitlements/pricing imports the page
// itself reads from (the hard rule applies here too, not just to visible
// JSX) rather than the hand-typed "$12/mo or $96/yr" the pre-T4 page used.
export const metadata: Metadata = {
  title: "Pricing",
  description: `Free forever for ${PLAN_LIMITS.free.dynamicCodes} dynamic codes. Pro is $${MONTHLY_USD}/mo or $${ANNUAL_USD}/yr. Every printed code keeps redirecting on downgrade.`,
};

/** Matrix cell renderer — count rows (row.freeIncluded === undefined) print
 *  their text plain; capability rows add a check glyph when included, so
 *  the honest phrasing from lib/pricing.ts (never a bare true/false) still
 *  reads as scannable at a glance. Unchanged from the pre-T4 page. */
function MatrixValue({ value, included }: { value: string; included?: boolean }) {
  if (included === undefined) {
    return <span className="text-sm text-foreground">{value}</span>;
  }
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 text-sm",
        included ? "text-foreground" : "text-muted-foreground",
      )}
    >
      {included && <Check className="size-3.5 shrink-0 text-primary" aria-hidden />}
      {value}
    </span>
  );
}

/**
 * Banded feature matrix — a hand-rolled `<table>` (not the vendored
 * `components/ui/table.tsx`, which ships `"use client"`) so /pricing stays
 * fully static, same reasoning `comparison-section.tsx` already established
 * on the landing. Every row comes from `PRICING_MATRIX_BANDS`
 * (lib/pricing.ts), itself a pure grouping over `PRICING_ROWS` — no row
 * dropped, no new claim, `pricing.test.ts` proves the coverage.
 *
 * Sticky band headers: `sticky top-24` matches the nav-clearance value this
 * codebase already uses elsewhere (`Section`'s own `scroll-mt-24`,
 * `/developers`' `sticky top-24` TOC rail) rather than inventing a new
 * offset.
 *
 * No `overflow-x-auto` on the outer wrapper, unlike `comparison-section.tsx`
 * — verified live (production build, browser-pane DOM inspection) that it
 * breaks the sticky headers on THIS table specifically: CSS's overflow
 * computed-value rule forces `overflow-y` to `auto` whenever `overflow-x` is
 * non-`visible` and `overflow-y` is left unset ("if one of overflow-x/-y is
 * `visible` and the other isn't, the `visible` one computes to `auto`" —
 * there's no way to have exactly one axis scroll), which silently turns the
 * wrapper into "the nearest ancestor with a scrolling mechanism" for
 * `position: sticky` purposes even though it never actually scrolls
 * (`scrollHeight === clientHeight`, verified). Every sticky `<th>` then
 * contains itself to THAT box's short scrollport instead of the page,
 * which pulls each one down to `96px` from the wrapper's own top edge
 * rather than the page's, stacking them on top of each other and the row
 * right below them. Unlike the 4-competitor comparison table, this one is
 * only 3 columns of short values, so it doesn't need the horizontal-scroll
 * safety net anyway — cells wrap instead (no `whitespace-nowrap` anywhere
 * here). Corner rounding is handled per-cell instead of via
 * `overflow-hidden` clipping (`rounded-tl-2xl`/`rounded-tr-2xl`/
 * `rounded-bl-2xl`/`rounded-br-2xl` on the outermost cells), the same
 * technique `comparison-section.tsx` uses for its own QRCDN column — this
 * table avoids `overflow-hidden` too, since that (unlike `overflow-x-auto`
 * alone) would unambiguously create the same unwanted sticky-containment
 * problem on BOTH axes.
 */
function PricingMatrix() {
  const lastBand = PRICING_MATRIX_BANDS[PRICING_MATRIX_BANDS.length - 1];
  const lastRowKey = lastBand?.rows[lastBand.rows.length - 1]?.key;

  return (
    <div className="rounded-2xl border border-border/60 bg-card/60">
      <table className="w-full border-collapse text-left">
        <thead>
          <tr>
            <th
              scope="col"
              className="rounded-tl-2xl px-5 py-3 text-xs font-medium uppercase tracking-wide text-muted-foreground"
            >
              Feature
            </th>
            <th
              scope="col"
              className="px-5 py-3 text-xs font-medium uppercase tracking-wide text-muted-foreground"
            >
              Free
            </th>
            <th
              scope="col"
              className="rounded-tr-2xl px-5 py-3 text-xs font-medium uppercase tracking-wide text-muted-foreground"
            >
              Pro
            </th>
          </tr>
        </thead>
        <tbody>
          {PRICING_MATRIX_BANDS.map((band) => (
            <Fragment key={band.name}>
              <tr>
                <th
                  scope="colgroup"
                  colSpan={3}
                  className="sticky top-24 z-10 border-y border-border/60 bg-muted px-5 py-2 text-left font-mono text-[11px] font-semibold uppercase tracking-[0.15em] text-muted-foreground"
                >
                  {band.name}
                </th>
              </tr>
              {band.rows.map((row) => {
                const isLastRow = row.key === lastRowKey;
                return (
                  <tr key={row.key}>
                    <td
                      className={cn(
                        "border-t border-border/60 px-5 py-3 text-sm font-medium text-foreground",
                        isLastRow && "rounded-bl-2xl",
                      )}
                    >
                      {row.label}
                    </td>
                    <td className="border-t border-border/60 px-5 py-3">
                      <MatrixValue value={row.free} included={row.freeIncluded} />
                    </td>
                    <td
                      className={cn(
                        "border-t border-border/60 px-5 py-3",
                        isLastRow && "rounded-br-2xl",
                      )}
                    >
                      <MatrixValue value={row.pro} included={row.proIncluded} />
                    </td>
                  </tr>
                );
              })}
            </Fragment>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function PricingPage() {
  return (
    <>
      {/* Poster head + plan cards. Plain eyebrow, no ordinal — /pricing
          doesn't use the landing's numbered sections. titleAs="h1" reaches
          text-display (the "one true page-title context" SectionHeading's
          own doc comment reserves that scale for). */}
      <Section divider="none">
        <SectionHeading
          eyebrow="Pricing"
          titleAs="h1"
          title="Two plans. Every number on the page."
          lede={
            <>
              Free gets {PLAN_LIMITS.free.dynamicCodes} dynamic codes that never stop
              redirecting. Pro is ${ANNUAL_MONTHLY_EQUIV_USD}/mo billed annually, or $
              {MONTHLY_USD} monthly. No quote form, no call.
            </>
          }
        />

        <SectionBody className="mt-10 max-w-4xl">
          <PricingPlans />
        </SectionBody>
      </Section>

      {/* Banded matrix. */}
      <Section surface="tint" divider="none">
        <SectionHeading
          eyebrow="Compare"
          title="Free and Pro, side by side."
          lede="Grouped the way the product works: codes, design, analytics, access, and API."
          className="mb-10"
        />

        <SectionBody>
          <PricingMatrix />
        </SectionBody>
      </Section>

      {/* Guarantee band — a real full-bleed Section, not a bordered callout
          card. Mono strip text is the deck-04 guarantee line verbatim (same
          styled-span treatment dynamic-codes-section.tsx already uses for
          this exact sentence). */}
      <Section variant="band" surface="default">
        <SectionBody className="flex flex-col items-center gap-6 text-center">
          <Eyebrow>Guarantee</Eyebrow>
          <p className="max-w-2xl text-h3 font-display font-semibold text-foreground">
            The floor is the promise: downgrading pauses growth, never print.
          </p>
          <MonoStrip>
            <span className="text-foreground">your code never dies</span>: free codes are
            never deactivated, and a downgrade never breaks a printed code.
          </MonoStrip>
        </SectionBody>
      </Section>

      {/* FAQ — split Section: heading + a short aside note left, the
          existing Q&A accordion right. Satisfies the dead-measure ban (the
          narrow heading column is never alone in its row — the FAQ list
          sits beside it as the full-measure counterpart). */}
      <Section variant="split" surface="tint" divider="none">
        <div className="grid gap-10 lg:grid-cols-[20rem_1fr] lg:gap-16">
          <SectionBody className="flex flex-col gap-4">
            <SectionHeading
              eyebrow="Questions"
              title="Before you pick a plan."
              lede="Straight answers, starting with the one everyone actually asks first."
              reveal={false}
            />
            <p className="text-sm text-muted-foreground">
              Still deciding?{" "}
              <a
                href="mailto:hello@qrcdn.com"
                className="text-foreground underline-offset-4 hover:underline"
              >
                hello@qrcdn.com
              </a>{" "}
              reaches a person, not a form.
            </p>
          </SectionBody>

          <SectionBody delay={0.15}>
            <PricingFaq />
          </SectionBody>
        </div>
      </Section>

      {/* Closing, air rhythm. */}
      <Section variant="centered" rhythm="air" surface="tint">
        <SectionHeading titleAs="h2" title="Start free. Upgrade when you print at scale." />

        <SectionBody delay={0.15} className="mt-8 flex flex-col items-center">
          <Button
            asChild
            size="lg"
            className="h-12 rounded-full px-7 text-base shadow-lg shadow-primary/25"
          >
            <Link href="/login">Start free</Link>
          </Button>
        </SectionBody>
      </Section>
    </>
  );
}
