import type { Metadata } from "next";
import Link from "next/link";
import { Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Eyebrow, ModuleMark, Reveal } from "@/components/brand/magic";
import { PricingFaq } from "@/components/marketing/pricing-faq";
import { PricingPlans } from "@/components/marketing/pricing-plans";
import { PLAN_LIMITS } from "@/lib/entitlements";
import { PRICING_ROWS } from "@/lib/pricing";
import { cn } from "@/lib/utils";

// Title/description only — file-based opengraph-image.png (+ .alt.txt,
// generated by scripts/generate-brand-images.ts) owns the imagery; Next's
// metadata merge is shallow, so setting any part of `openGraph` here would
// replace the root layout's whole object instead of extending it. `title`
// is a plain string on purpose — the root layout's `title.template`
// ("%s · QRCDN") supplies the suffix (docs/guides/p9-marketing.md's route
// architecture note; verified against the bundled Next 16 metadata docs).
export const metadata: Metadata = {
  title: "Pricing",
  description:
    "Free forever for a few dynamic codes. Pro is $12/mo or $96/yr. Downgrade anytime — every printed code keeps redirecting, we cap features, never your codes.",
};

/** Matrix cell renderer — count rows (row.freeIncluded === undefined) print
 *  their text plain; capability rows add a check glyph when included, so
 *  the honest phrasing from lib/pricing.ts (never a bare true/false) still
 *  reads as scannable at a glance. */
function MatrixValue({ value, included }: { value: string; included?: boolean }) {
  if (included === undefined) {
    return <span className="text-sm text-foreground">{value}</span>;
  }
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 text-sm",
        included ? "text-foreground" : "text-muted-foreground",
      )}
    >
      {included && <Check className="size-3.5 shrink-0 text-primary" aria-hidden />}
      {value}
    </span>
  );
}

export default function PricingPage() {
  return (
    <>
      <section>
        <div className="mx-auto max-w-6xl px-6 pt-16 pb-4 sm:pt-24">
          <Reveal className="max-w-2xl">
            <Eyebrow>Pricing</Eyebrow>
            <h1 className="font-display text-5xl font-bold tracking-tight sm:text-6xl">
              Simple, honest pricing.
            </h1>
            <p className="mt-4 text-lg text-muted-foreground">
              No hidden tiers. No disappearing codes. Every printed code keeps working,
              whichever plan you pick.
            </p>
          </Reveal>
        </div>
      </section>

      <section>
        <div className="mx-auto max-w-6xl px-6 py-12">
          <Reveal delay={0.1} className="max-w-4xl">
            <PricingPlans />
          </Reveal>
        </div>
      </section>

      <section className="border-t border-border/60">
        <div className="mx-auto max-w-6xl px-6 py-16">
          <Reveal className="max-w-4xl">
            <Eyebrow>Compare</Eyebrow>
            <h2 className="font-display text-3xl font-semibold tracking-tight">
              Every plan, in full.
            </h2>
            <p className="mt-2 max-w-xl text-muted-foreground">
              The same limits the app enforces — nothing here is marketing rounding.
            </p>

            <div className="mt-8 overflow-hidden rounded-2xl border border-border/60 bg-card/60">
              <Table>
                <TableHeader>
                  <TableRow className="hover:bg-transparent">
                    <TableHead>Feature</TableHead>
                    <TableHead>Free</TableHead>
                    <TableHead>Pro</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {PRICING_ROWS.map((row) => (
                    <TableRow key={row.key} className="hover:bg-transparent">
                      <TableCell className="font-medium text-foreground">{row.label}</TableCell>
                      <TableCell>
                        <MatrixValue value={row.free} included={row.freeIncluded} />
                      </TableCell>
                      <TableCell>
                        <MatrixValue value={row.pro} included={row.proIncluded} />
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </Reveal>
        </div>
      </section>

      <section>
        <div className="mx-auto max-w-6xl px-6">
          <Reveal className="max-w-4xl rounded-2xl border border-border/60 bg-card/60 px-6 py-5 sm:flex sm:items-center sm:gap-4">
            <ModuleMark className="mb-2 size-3.5 shrink-0 text-primary sm:mb-0" />
            <p className="text-sm">
              <span className="font-medium text-foreground">
                We cap features, never your printed codes.
              </span>{" "}
              <span className="text-muted-foreground">
                Downgrade below {PLAN_LIMITS.free.dynamicCodes} dynamic codes and the rest go
                read-only — every one keeps redirecting, forever.
              </span>
            </p>
          </Reveal>
        </div>
      </section>

      <section className="mt-4">
        <div className="mx-auto max-w-6xl px-6 py-16">
          <Reveal className="max-w-3xl">
            <Eyebrow>Questions</Eyebrow>
            <h2 className="font-display text-3xl font-semibold tracking-tight">
              Before you pick a plan.
            </h2>
            <div className="mt-8">
              <PricingFaq />
            </div>
          </Reveal>
        </div>
      </section>

      <section className="border-t border-border/60">
        <div className="mx-auto max-w-6xl px-6 py-20">
          <Reveal className="max-w-2xl">
            <h2 className="font-display text-3xl font-semibold tracking-tight sm:text-4xl">
              Set up your first code. It stays free.
            </h2>
            <p className="mt-3 text-muted-foreground">
              No credit card, no trial clock. Upgrade whenever Pro checkout opens — your codes
              carry over either way.
            </p>
            <Button asChild size="lg" className="mt-6">
              <Link href="/login">Start free</Link>
            </Button>
          </Reveal>
        </div>
      </section>
    </>
  );
}
