import type { Metadata } from "next";
import { Hero } from "@/components/marketing/hero";
import { HowItWorksSection } from "@/components/marketing/how-it-works-section";
import { Playground } from "@/components/marketing/playground";
import { BrandSystemSection } from "@/components/marketing/brand-system-section";
import { DynamicCodesSection } from "@/components/marketing/dynamic-codes-section";
import { GuardrailsSection } from "@/components/marketing/guardrails-section";
import { AnalyticsSection } from "@/components/marketing/analytics-section";
import { ApiSection } from "@/components/marketing/api-section";
import { ComparisonSection } from "@/components/marketing/comparison-section";
import { OpenSourceSection } from "@/components/marketing/open-source-section";
import { ManifestoSection } from "@/components/marketing/manifesto-section";
import { PricingTeaser } from "@/components/marketing/pricing-teaser";
import { ClosingSection } from "@/components/marketing/closing-section";

// Title/description only, and only `description` is set here: the root
// layout's `title.default` ("QRCDN: QR codes with a brand system") IS the
// site title for `/`, so this page deliberately does not export a `title`
// (p9-marketing.md's route architecture note; Next's metadata resolution
// inherits the nearest ancestor's resolved title as-is when a segment omits
// its own). The homepage OG image (app/(marketing)/opengraph-image.png,
// generated by scripts/generate-brand-images.ts in P9-U1) attaches
// automatically via the file-convention colocated in this same route
// segment — no code change needed here.
export const metadata: Metadata = {
  description:
    "Design your brand's QR identity once, then generate static or dynamic codes on persistent short URLs: retargetable forever, measured to the scan, free forever for a few dynamic codes.",
};

// The atomic swap (P9-U2): this file replaces the create-next-app scaffold
// that used to live at app/page.tsx (deleted in the same commit). Every
// section below is a fresh components/marketing/* file, harvested-for-
// pattern from components/explore/* rather than imported from it (per
// docs/guides/p9-marketing.md — /explore is deleted at P9-U5). No data
// fetching, no dynamic APIs anywhere in the tree, so `/` renders fully
// static (`○ (Static)` in `next build` output).
//
// P9.5-T3a: every section below (including the two new ones,
// HowItWorksSection/ClosingSection) is now built on the T1
// Section/SectionHeading/SectionBody primitives, carrying the copy deck
// v3 eyebrow ordinals the deck itself uses.
//
// P9.7-V1: THIS FILE OWNS SECTION ORDER *AND* NUMBERING.
//
// Ordinals used to be hardcoded string literals inside each section file
// (`index="05"` living in guardrails-section.tsx, and so on). That meant the
// eyebrow numbering and the actual DOM order were two independent facts that
// nothing kept in sync: reordering two sections here left both of them
// displaying their old numbers, and neither the type system nor any test
// would have said a word. Since this round reorders sections and inserts two
// more, the page that decides the order now also supplies the numbers.
//
// Practical effect: inserting a section is one line here plus a renumber of
// the lines below it, all visible together in one file, instead of a literal
// bump in every downstream component.
//
// Surface alternation, per the Section system's rule (a hairline only between
// two same-surface neighbors; everywhere else the surface change is itself the
// seam): tint, floor, default, tint, floor, default, tint, default, floor,
// tint, default, closing default. The single same-surface adjacency is
// PricingTeaser -> ClosingSection, which is why ClosingSection is the one
// section on the page still carrying a hairline.
//
// Still to land in later units of this round: 01 Highlights (a bento, which
// takes over the hero pillar strip's job) and Access controls, between Dynamic
// links and Analytics. Both slot in here and everything below them renumbers
// in this file alone.
export default function HomePage() {
  return (
    <>
      <Hero />
      <HowItWorksSection index="01" />
      <Playground index="02" />
      <BrandSystemSection index="03" />
      <DynamicCodesSection index="04" />
      <AnalyticsSection index="05" />
      <GuardrailsSection index="06" />
      <ApiSection index="07" />
      <ComparisonSection index="08" />
      <OpenSourceSection index="09" />
      <ManifestoSection index="10" />
      <PricingTeaser index="11" />
      {/* Explicit title, even though it matches the component default: that
          default is also what /features/dynamic-codes renders with zero props,
          so leaving this implicit means a landing copy change silently rewrites
          a feature page's closing heading too. */}
      <ClosingSection title="Create your first code in minutes." />
    </>
  );
}
