import type { Metadata } from "next";
import { Hero } from "@/components/marketing/hero";
import { HowItWorksSection } from "@/components/marketing/how-it-works-section";
import { IndexWallSection } from "@/components/marketing/index-wall";
import { StudioSection } from "@/components/marketing/studio-section";
import { BrandSystemSection } from "@/components/marketing/brand-system-section";
import { DynamicCodesSection } from "@/components/marketing/dynamic-codes-section";
import { AccessControlsSection } from "@/components/marketing/access-controls-section";
import { GuardrailsSection } from "@/components/marketing/guardrails-section";
import { AnalyticsSection } from "@/components/marketing/analytics-section";
import { ApiSection } from "@/components/marketing/api-section";
import { ComparisonSection } from "@/components/marketing/comparison-section";
import { OpenSourceSection } from "@/components/marketing/open-source-section";
import { ManifestoSection } from "@/components/marketing/manifesto-section";
import { PricingTeaser } from "@/components/marketing/pricing-teaser";
import { LandingClosing } from "@/components/marketing/landing-closing";

// Title/description only, and only `description` is set here: the root
// layout's `title.default` ("QRCDN: QR codes with a brand system") IS the
// site title for `/`, so this page deliberately does not export a `title`
// (p9-marketing.md's route architecture note; Next's metadata resolution
// inherits the nearest ancestor's resolved title as-is when a segment omits
// its own). The homepage OG image (app/(marketing)/opengraph-image.png,
// generated by scripts/generate-brand-images.ts in P9-U1) attaches
// automatically via the file-convention colocated in this same route
// segment — no code change needed here.
export const metadata: Metadata = {
  description:
    "Design your brand's QR identity once, then generate static or dynamic codes on persistent short URLs: retargetable forever, measured to the scan, free forever for a few dynamic codes.",
};

// The atomic swap (P9-U2): this file replaces the create-next-app scaffold
// that used to live at app/page.tsx (deleted in the same commit). Every
// section below is a fresh components/marketing/* file, harvested-for-
// pattern from components/explore/* rather than imported from it (per
// docs/guides/p9-marketing.md — /explore is deleted at P9-U5). No data
// fetching, no dynamic APIs anywhere in the tree, so `/` renders fully
// static (`○ (Static)` in `next build` output).
//
// P9.5-T3a: every section below (including the two new ones,
// HowItWorksSection/ClosingSection) is now built on the T1
// Section/SectionHeading/SectionBody primitives, carrying the copy deck
// v3 eyebrow ordinals the deck itself uses.
//
// P9.7-V1: THIS FILE OWNS SECTION ORDER *AND* NUMBERING.
//
// Ordinals used to be hardcoded string literals inside each section file
// (`index="05"` living in guardrails-section.tsx, and so on). That meant the
// eyebrow numbering and the actual DOM order were two independent facts that
// nothing kept in sync: reordering two sections here left both of them
// displaying their old numbers, and neither the type system nor any test
// would have said a word. Since this round reorders sections and inserts two
// more, the page that decides the order now also supplies the numbers.
//
// Practical effect: inserting a section is one line here plus a renumber of
// the lines below it, all visible together in one file, instead of a literal
// bump in every downstream component.
//
// Surface alternation, per the Section system's rule: a hairline only between
// two same-surface neighbors; everywhere else the surface change is itself the
// seam. Each section declares its own surface in its own file — no enumerated
// list here, it drifted every time the order changed.
//
// P9.10-D7 retired the last one. PricingTeaser -> the closing was the page's
// only same-surface adjacency, so the closing was the one section still
// carrying a hairline; 13 now ends on a full-length contact row, which gives
// the seam nothing left to separate. The landing carries NO hairline dividers
// at all today, and adding one back means re-checking that rule first.
//
// P9.7-V2 proved the ownership model out: inserting the Highlights bento at 01
// renumbered eleven sections, and the entire change was the block below.
// Access controls (06) landed the same way at P9.7-V4.
//
// P9.10-D4 swapped 01 and 02 and nothing else. The highlights bento retired
// (it enumerated the product a third time in one screen and drew two of the
// filmstrip's own artworks a second time), the filmstrip took 01 so the
// hero's real engine renders hand off to more real renders, and the index
// wall took 02 as the ramp into the deep page. Because the two sections
// exchanged ordinals rather than one being inserted, 03 through 13 did not
// move at all — the opposite of the eleven-section renumber P9.7-V2 caused.
//
// How it works takes `tint` at 01 (the bento's old surface): `variant="band"`
// forces `divider="none"`, and hero and band are both `default`, so promoted
// unchanged there would be no seam between the hero and the page's first
// section at all. The wall then sits on `default` and 03 keeps `floor`.
//
// P9.9-C0: this file also owns the heading ladder. Every section's title
// used to render at one of two fixed sizes decided inside its own component
// (`titleAs`'s default resolution in section.tsx) — no page-level view of
// which sections read louder or quieter than their neighbors, the same
// problem ordinals had before P9.7-V1. The ladder has three registers: Loud
// (`--text-h1`, the hero's own scale) for the one section that should hit as
// hard as the hero; Normal (`--text-h2-lg`, new this unit) for the bulk of
// the page; Quiet (`--text-h2`, `SectionHeading`'s plain default) for
// sections that should recede. `titleSize="h2-lg"` below is Normal;
// `titleSize="h1"` on ManifestoSection is Loud (it stays a semantic `<h2>` —
// `titleAs` defaults to `"h2"` — so the one-h1-per-page invariant still
// holds, only the visual size reaches display register); GuardrailsSection/
// ComparisonSection/OpenSourceSection take no `titleSize` prop at all and
// stay Quiet. Same rationale as the ordinals rule above: the hierarchy is
// one visible block here, not literals scattered across eleven files.
export default function HomePage() {
  return (
    <>
      <Hero />
      <HowItWorksSection index="01" titleSize="h2-lg" />
      {/* No titleSize: the wall owns its own label register (see the
          component). It is the one section on the page whose heading is
          deliberately quieter than its body. */}
      <IndexWallSection index="02" />
      <StudioSection index="03" titleSize="h2-lg" />
      <BrandSystemSection index="04" titleSize="h2-lg" />
      <DynamicCodesSection index="05" titleSize="h2-lg" />
      <AccessControlsSection index="06" titleSize="h2-lg" />
      <AnalyticsSection index="07" titleSize="h2-lg" />
      <GuardrailsSection index="08" />
      <ApiSection index="09" titleSize="h2-lg" />
      <ComparisonSection index="10" />
      <OpenSourceSection index="11" />
      <ManifestoSection index="12" titleSize="h1" />
      <PricingTeaser index="13" titleSize="h2-lg" />
      {/* P9.10-D7: the landing's closing is its own component now. It is
          the one ending on the site carrying the aurora budget's closing
          placement, plus the drifting code field behind it, and forking
          the shared ClosingSection to get either would have restyled the
          four feature pages nobody asked about. ClosingSection stays
          exactly as it was for /features/*, still taking an explicit title
          at every call site so a landing copy change can never silently
          rewrite a feature page's heading. */}
      <LandingClosing />
    </>
  );
}
